<a href="https://colab.research.google.com/github/moonjune/test-repo/blob/master/rnn_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.12

     |████████████████████████████████| 83.1MB 1.3MB/s 
     |████████████████████████████████| 3.1MB 35.7MB/s 
  Found existing installation: tensorboard 1.13.1
    Uninstalling tensorboard-1.13.1:
      Successfully uninstalled tensorboard-1.13.1
  Found existing installation: tensorflow 1.13.1
    Uninstalling tensorflow-1.13.1:
      Successfully uninstalled tensorflow-1.13.1


In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

print(tf.__version__)
tf.enable_eager_execution()

1.12.0


In [0]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [11]:
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size) # 텐서플로 케라스에서 데려온 layers 라이브러리에 있는 셀 함수. units를 인수로 받음
rnn = layers.RNN(cell, return_sequences = True, return_state = True) 
# 정의된 셀을 인자로 받는 신경망 함수
# return_sequences: 아웃풋을 마지막만 반환할지(1?) 전체 다 할건지 결정, 여기선 셀이 하나라서 하나만 나오나 봄(Waa Wax Way는?)
# return_state: 상태를 반환.. 위나 아래나 둘 다 state를 반환한 것이다. 4차원 짜리를 2차원의, 'h'를 2개의 수로 표현한 것
outputs, states = rnn(x_data)

print('x_data: {}, shape : {}'.format(x_data, x_data.shape))
print('outputs: {}, shape : {}'.format(outputs, outputs.shape))
print('states: {}, shape : {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape : (1, 1, 4)
outputs: [[[-0.42005527  0.2170559 ]]], shape : (1, 1, 2)
states: [[-0.42005527  0.2170559 ]], shape : (1, 2)


In [12]:
rnn = layers.SimpleRNN(units = hidden_size, return_sequences = True,
                      return_state = True)
# 셀을 정의하고 rnn에 넣었던 위 식과 다른 표시법. 

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.3397314  0.11883394]]], shape: (1, 1, 2)
states: [[0.3397314  0.11883394]], shape: (1, 2)


In [21]:
x_data = np.array([[h, e, l, l, o]], dtype = np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units = 2, return_sequences = True, return_state = True)

outputs, state = rnn(x_data)


print('x_data : {}, shape{} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape(1, 5, 4) 

outputs: [[[ 0.67038167 -0.21768308]
  [ 0.53954494  0.9223484 ]
  [ 0.50497276  0.36870682]
  [ 0.00405429  0.41591707]
  [-0.16614102  0.18127671]]], shape: (1, 5, 2) 

states: [[0.3397314  0.11883394]], shape: (1, 2)
