<a href="https://colab.research.google.com/github/moonjune/test-repo/blob/master/rnn_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.12

     |████████████████████████████████| 83.1MB 417kB/s 
     |████████████████████████████████| 3.1MB 34.0MB/s 
  Found existing installation: tensorboard 1.13.1
    Uninstalling tensorboard-1.13.1:
      Successfully uninstalled tensorboard-1.13.1
  Found existing installation: tensorflow 1.13.1
    Uninstalling tensorflow-1.13.1:
      Successfully uninstalled tensorflow-1.13.1


In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

print(tf.__version__)
tf.enable_eager_execution()

1.12.0


In [0]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [4]:
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size) # 텐서플로 케라스에서 데려온 layers 라이브러리에 있는 셀 함수. units를 인수로 받음
rnn = layers.RNN(cell, return_sequences = True, return_state = True) 
# 정의된 셀을 인자로 받는 신경망 함수
# return_sequences: 아웃풋을 마지막만 반환할지(1?) 전체 다 할건지 결정, 여기선 셀이 하나라서 하나만 나오나 봄(Waa Wax Way는?)
# return_state: 상태를 반환.. 위나 아래나 둘 다 state를 반환한 것이다. 4차원 짜리를 2차원의, 'h'를 2개의 수로 표현한 것
outputs, states = rnn(x_data)

print('x_data: {}, shape : {}'.format(x_data, x_data.shape))
print('outputs: {}, shape : {}'.format(outputs, outputs.shape))
print('states: {}, shape : {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape : (1, 1, 4)
outputs: [[[0.4263243  0.60274637]]], shape : (1, 1, 2)
states: [[0.4263243  0.60274637]], shape : (1, 2)


In [5]:
rnn = layers.SimpleRNN(units = hidden_size, return_sequences = True,
                      return_state = True)
# 셀을 정의하고 rnn에 넣었던 위 식과 다른 표시법. 

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.67922044  0.12051022]]], shape: (1, 1, 2)
states: [[-0.67922044  0.12051022]], shape: (1, 2)


In [13]:
x_data = np.array([[h, e, l, l, o]], dtype = np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units = 2, return_sequences = True, return_state = True)
# 시퀀스는 h,e,l,l,o를 구성하는 5개에 대한 박스 값을 의미한다.. 그런데 응애 state는 뭔가?
# 가장 유력한 추정은 Waa이다. 얘는 불변이라 1개의 값이고 1,4였던 값을 1,2로 바꾸기 위해선 2가 들어가야 하는데...
# 뭔가 실수가 있어서 정정되었음. state는 마지막값을 의미함

outputs, state = rnn(x_data)


print('x_data : {}, shape{} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(state, state.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape(1, 5, 4) 

outputs: [[[ 0.41113684 -0.7473485 ]
  [-0.38623387 -0.4041295 ]
  [ 0.09279767  0.2903303 ]
  [ 0.5970044  -0.29017586]
  [-0.3213257  -0.83620524]]], shape: (1, 5, 2) 

states: [[-0.3213257  -0.83620524]], shape: (1, 2)


In [14]:
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype = np.float32)

hidden_size = 2
#히든 사이즈는 최종적으로 2가 되도록 만들라는 명령임.. 행렬 형태를 맞춘 행렬곱을 해줘야 할텐데 이걸 이 명령 하나로 끝내는 거
rnn = layers.SimpleRNN(units = 2, return_sequences = False, return_state = True)
outputs, states = rnn(x_data)
# 예제에서 출력한 states는 가장 마지막 단에서 만들어진 히든값이고 이는 return_sequences의 가장 마지막 값과 같다. 
# 이걸 계속 봐온 이유는 무엇일까...
#

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))


x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[ 0.8115094  -0.8678043 ]
 [ 0.92047393  0.6977403 ]
 [ 0.91155434  0.57665396]], shape: (3, 2) 

states: [[ 0.8115094  -0.8678043 ]
 [ 0.92047393  0.6977403 ]
 [ 0.91155434  0.57665396]], shape: (3, 2)
